# Generated by Django 5.2.6 on 2025-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
