# Generated by Django 5.2.6 on 2025-09-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.CharField(max_length=30, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_compra', models.CharField(max_length=20)),
                ('unidad_venta', models.CharField(max_length=20)),
                ('factor_conversion', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('punto_reorden', models.IntegerField(blank=True, null=True)),
                ('perecible', models.BooleanField(default=False)),
                ('control_por_lote', models.BooleanField(default=False)),
                ('control_por_serie', models.BooleanField(default=False)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('ficha_tecnica_url', models.URLField(blank=True, null=True)),
                ('stock_actual', models.IntegerField(default=0)),
                ('alerta_bajo_stock', models.BooleanField(default=False)),
                ('alerta_por_vencer', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
